# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-03 07:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180103_0741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='pub_time',
        ),
    ]
